name: frontend

services:
  ui:
    build: 
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint: npm run dev
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=https://zpsprlbc34.execute-api.us-east-1.amazonaws.com/v1/wallet

volumes:
  node_modules: