name: frontend

services:
  ui:
    build: 
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint: npm run dev
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=https://c2czve35knwprz6itpwpuw6za40htndh.lambda-url.us-east-1.on.aws/api      

volumes:
  node_modules: