#!/bin/bash
USAGE="
Wallet

Repository maintenance

Usage:

  $(basename $0) [command] <args>

Available Commands

  run    run local go application
  build  build go http application

Examples:

  # local development
  $(basename $0) run
"

if [[ $1 == "run" ]]; then    
    docker run --env-file .env -it \
        -v $PWD:/app \
        -w /app \
        --rm \
        --network host \
        --name golang golang:1.21 ./out/http
    exit 0
fi

if [[ $1 == "lambda" ]]; then    
    docker run --env-file .env -it \
        -v $PWD:/app \
        -w /app \
        --rm \
        --network host \
        --name golang golang:1.21 ./out/bootstrap
    exit 0
fi

if [[ $1 == "build" ]]; then    
    docker exec \
        -w /home/gopher/src/wallet/ \
        -it wallet make build-http
    exit 0
fi;

echo "unexpected argument"
exit 1
